require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MailTmpsController do

  # This should return the minimal set of attributes required to create a valid
  # MailTmp. As you add validations to MailTmp, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MailTmpsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all mail_tmps as @mail_tmps" do
      mail_tmp = MailTmp.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mail_tmps).should eq([mail_tmp])
    end
  end

  describe "GET show" do
    it "assigns the requested mail_tmp as @mail_tmp" do
      mail_tmp = MailTmp.create! valid_attributes
      get :show, {:id => mail_tmp.to_param}, valid_session
      assigns(:mail_tmp).should eq(mail_tmp)
    end
  end

  describe "GET new" do
    it "assigns a new mail_tmp as @mail_tmp" do
      get :new, {}, valid_session
      assigns(:mail_tmp).should be_a_new(MailTmp)
    end
  end

  describe "GET edit" do
    it "assigns the requested mail_tmp as @mail_tmp" do
      mail_tmp = MailTmp.create! valid_attributes
      get :edit, {:id => mail_tmp.to_param}, valid_session
      assigns(:mail_tmp).should eq(mail_tmp)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MailTmp" do
        expect {
          post :create, {:mail_tmp => valid_attributes}, valid_session
        }.to change(MailTmp, :count).by(1)
      end

      it "assigns a newly created mail_tmp as @mail_tmp" do
        post :create, {:mail_tmp => valid_attributes}, valid_session
        assigns(:mail_tmp).should be_a(MailTmp)
        assigns(:mail_tmp).should be_persisted
      end

      it "redirects to the created mail_tmp" do
        post :create, {:mail_tmp => valid_attributes}, valid_session
        response.should redirect_to(MailTmp.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mail_tmp as @mail_tmp" do
        # Trigger the behavior that occurs when invalid params are submitted
        MailTmp.any_instance.stub(:save).and_return(false)
        post :create, {:mail_tmp => { "user" => "invalid value" }}, valid_session
        assigns(:mail_tmp).should be_a_new(MailTmp)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MailTmp.any_instance.stub(:save).and_return(false)
        post :create, {:mail_tmp => { "user" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mail_tmp" do
        mail_tmp = MailTmp.create! valid_attributes
        # Assuming there are no other mail_tmps in the database, this
        # specifies that the MailTmp created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MailTmp.any_instance.should_receive(:update_attributes).with({ "user" => "" })
        put :update, {:id => mail_tmp.to_param, :mail_tmp => { "user" => "" }}, valid_session
      end

      it "assigns the requested mail_tmp as @mail_tmp" do
        mail_tmp = MailTmp.create! valid_attributes
        put :update, {:id => mail_tmp.to_param, :mail_tmp => valid_attributes}, valid_session
        assigns(:mail_tmp).should eq(mail_tmp)
      end

      it "redirects to the mail_tmp" do
        mail_tmp = MailTmp.create! valid_attributes
        put :update, {:id => mail_tmp.to_param, :mail_tmp => valid_attributes}, valid_session
        response.should redirect_to(mail_tmp)
      end
    end

    describe "with invalid params" do
      it "assigns the mail_tmp as @mail_tmp" do
        mail_tmp = MailTmp.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MailTmp.any_instance.stub(:save).and_return(false)
        put :update, {:id => mail_tmp.to_param, :mail_tmp => { "user" => "invalid value" }}, valid_session
        assigns(:mail_tmp).should eq(mail_tmp)
      end

      it "re-renders the 'edit' template" do
        mail_tmp = MailTmp.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MailTmp.any_instance.stub(:save).and_return(false)
        put :update, {:id => mail_tmp.to_param, :mail_tmp => { "user" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mail_tmp" do
      mail_tmp = MailTmp.create! valid_attributes
      expect {
        delete :destroy, {:id => mail_tmp.to_param}, valid_session
      }.to change(MailTmp, :count).by(-1)
    end

    it "redirects to the mail_tmps list" do
      mail_tmp = MailTmp.create! valid_attributes
      delete :destroy, {:id => mail_tmp.to_param}, valid_session
      response.should redirect_to(mail_tmps_url)
    end
  end

end
