require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SmsLogsController do

  # This should return the minimal set of attributes required to create a valid
  # SmsLog. As you add validations to SmsLog, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SmsLogsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all sms_logs as @sms_logs" do
      sms_log = SmsLog.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sms_logs).should eq([sms_log])
    end
  end

  describe "GET show" do
    it "assigns the requested sms_log as @sms_log" do
      sms_log = SmsLog.create! valid_attributes
      get :show, {:id => sms_log.to_param}, valid_session
      assigns(:sms_log).should eq(sms_log)
    end
  end

  describe "GET new" do
    it "assigns a new sms_log as @sms_log" do
      get :new, {}, valid_session
      assigns(:sms_log).should be_a_new(SmsLog)
    end
  end

  describe "GET edit" do
    it "assigns the requested sms_log as @sms_log" do
      sms_log = SmsLog.create! valid_attributes
      get :edit, {:id => sms_log.to_param}, valid_session
      assigns(:sms_log).should eq(sms_log)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SmsLog" do
        expect {
          post :create, {:sms_log => valid_attributes}, valid_session
        }.to change(SmsLog, :count).by(1)
      end

      it "assigns a newly created sms_log as @sms_log" do
        post :create, {:sms_log => valid_attributes}, valid_session
        assigns(:sms_log).should be_a(SmsLog)
        assigns(:sms_log).should be_persisted
      end

      it "redirects to the created sms_log" do
        post :create, {:sms_log => valid_attributes}, valid_session
        response.should redirect_to(SmsLog.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sms_log as @sms_log" do
        # Trigger the behavior that occurs when invalid params are submitted
        SmsLog.any_instance.stub(:save).and_return(false)
        post :create, {:sms_log => { "user" => "invalid value" }}, valid_session
        assigns(:sms_log).should be_a_new(SmsLog)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SmsLog.any_instance.stub(:save).and_return(false)
        post :create, {:sms_log => { "user" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sms_log" do
        sms_log = SmsLog.create! valid_attributes
        # Assuming there are no other sms_logs in the database, this
        # specifies that the SmsLog created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SmsLog.any_instance.should_receive(:update_attributes).with({ "user" => "" })
        put :update, {:id => sms_log.to_param, :sms_log => { "user" => "" }}, valid_session
      end

      it "assigns the requested sms_log as @sms_log" do
        sms_log = SmsLog.create! valid_attributes
        put :update, {:id => sms_log.to_param, :sms_log => valid_attributes}, valid_session
        assigns(:sms_log).should eq(sms_log)
      end

      it "redirects to the sms_log" do
        sms_log = SmsLog.create! valid_attributes
        put :update, {:id => sms_log.to_param, :sms_log => valid_attributes}, valid_session
        response.should redirect_to(sms_log)
      end
    end

    describe "with invalid params" do
      it "assigns the sms_log as @sms_log" do
        sms_log = SmsLog.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SmsLog.any_instance.stub(:save).and_return(false)
        put :update, {:id => sms_log.to_param, :sms_log => { "user" => "invalid value" }}, valid_session
        assigns(:sms_log).should eq(sms_log)
      end

      it "re-renders the 'edit' template" do
        sms_log = SmsLog.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SmsLog.any_instance.stub(:save).and_return(false)
        put :update, {:id => sms_log.to_param, :sms_log => { "user" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sms_log" do
      sms_log = SmsLog.create! valid_attributes
      expect {
        delete :destroy, {:id => sms_log.to_param}, valid_session
      }.to change(SmsLog, :count).by(-1)
    end

    it "redirects to the sms_logs list" do
      sms_log = SmsLog.create! valid_attributes
      delete :destroy, {:id => sms_log.to_param}, valid_session
      response.should redirect_to(sms_logs_url)
    end
  end

end
