require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SmsTmpsController do

  # This should return the minimal set of attributes required to create a valid
  # SmsTmp. As you add validations to SmsTmp, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SmsTmpsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all sms_tmps as @sms_tmps" do
      sms_tmp = SmsTmp.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sms_tmps).should eq([sms_tmp])
    end
  end

  describe "GET show" do
    it "assigns the requested sms_tmp as @sms_tmp" do
      sms_tmp = SmsTmp.create! valid_attributes
      get :show, {:id => sms_tmp.to_param}, valid_session
      assigns(:sms_tmp).should eq(sms_tmp)
    end
  end

  describe "GET new" do
    it "assigns a new sms_tmp as @sms_tmp" do
      get :new, {}, valid_session
      assigns(:sms_tmp).should be_a_new(SmsTmp)
    end
  end

  describe "GET edit" do
    it "assigns the requested sms_tmp as @sms_tmp" do
      sms_tmp = SmsTmp.create! valid_attributes
      get :edit, {:id => sms_tmp.to_param}, valid_session
      assigns(:sms_tmp).should eq(sms_tmp)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SmsTmp" do
        expect {
          post :create, {:sms_tmp => valid_attributes}, valid_session
        }.to change(SmsTmp, :count).by(1)
      end

      it "assigns a newly created sms_tmp as @sms_tmp" do
        post :create, {:sms_tmp => valid_attributes}, valid_session
        assigns(:sms_tmp).should be_a(SmsTmp)
        assigns(:sms_tmp).should be_persisted
      end

      it "redirects to the created sms_tmp" do
        post :create, {:sms_tmp => valid_attributes}, valid_session
        response.should redirect_to(SmsTmp.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sms_tmp as @sms_tmp" do
        # Trigger the behavior that occurs when invalid params are submitted
        SmsTmp.any_instance.stub(:save).and_return(false)
        post :create, {:sms_tmp => { "user" => "invalid value" }}, valid_session
        assigns(:sms_tmp).should be_a_new(SmsTmp)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SmsTmp.any_instance.stub(:save).and_return(false)
        post :create, {:sms_tmp => { "user" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sms_tmp" do
        sms_tmp = SmsTmp.create! valid_attributes
        # Assuming there are no other sms_tmps in the database, this
        # specifies that the SmsTmp created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SmsTmp.any_instance.should_receive(:update_attributes).with({ "user" => "" })
        put :update, {:id => sms_tmp.to_param, :sms_tmp => { "user" => "" }}, valid_session
      end

      it "assigns the requested sms_tmp as @sms_tmp" do
        sms_tmp = SmsTmp.create! valid_attributes
        put :update, {:id => sms_tmp.to_param, :sms_tmp => valid_attributes}, valid_session
        assigns(:sms_tmp).should eq(sms_tmp)
      end

      it "redirects to the sms_tmp" do
        sms_tmp = SmsTmp.create! valid_attributes
        put :update, {:id => sms_tmp.to_param, :sms_tmp => valid_attributes}, valid_session
        response.should redirect_to(sms_tmp)
      end
    end

    describe "with invalid params" do
      it "assigns the sms_tmp as @sms_tmp" do
        sms_tmp = SmsTmp.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SmsTmp.any_instance.stub(:save).and_return(false)
        put :update, {:id => sms_tmp.to_param, :sms_tmp => { "user" => "invalid value" }}, valid_session
        assigns(:sms_tmp).should eq(sms_tmp)
      end

      it "re-renders the 'edit' template" do
        sms_tmp = SmsTmp.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SmsTmp.any_instance.stub(:save).and_return(false)
        put :update, {:id => sms_tmp.to_param, :sms_tmp => { "user" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sms_tmp" do
      sms_tmp = SmsTmp.create! valid_attributes
      expect {
        delete :destroy, {:id => sms_tmp.to_param}, valid_session
      }.to change(SmsTmp, :count).by(-1)
    end

    it "redirects to the sms_tmps list" do
      sms_tmp = SmsTmp.create! valid_attributes
      delete :destroy, {:id => sms_tmp.to_param}, valid_session
      response.should redirect_to(sms_tmps_url)
    end
  end

end
